name: Publish patcher image
run-name: ${{ format('Publish runner image with NerdFonts {0} and FonteForge {1}', inputs.nf_version, inputs.ff_version) }}

on:
  workflow_dispatch:
    inputs:
      nf_version:
        description: 'NerdFonts version'
        required: true
      ff_version:
        description: 'FontForge version'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: patcher

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            nf${{ inputs.nf_version }}-ff${{ inputs.ff_version }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NERD_FONTS_VERSION=${{ inputs.nf_version }}
            FONT_FORGE_VERSION=${{ inputs.ff_version }}
          context: ./patcher
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
